# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ColorDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(510, 489)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 561, 651))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.listWidget = QtGui.QListWidget(self.tab_1)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 261, 171))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.pushButton_14 = QtGui.QPushButton(self.tab_1)
        self.pushButton_14.setGeometry(QtCore.QRect(380, 400, 112, 27))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 170, 261, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.colorbutton3 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton3.sizePolicy().hasHeightForWidth())
        self.colorbutton3.setSizePolicy(sizePolicy)
        self.colorbutton3.setText(_fromUtf8(""))
        self.colorbutton3.setObjectName(_fromUtf8("colorbutton3"))
        self.gridLayout.addWidget(self.colorbutton3, 0, 2, 1, 1)
        self.colorbutton4 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton4.sizePolicy().hasHeightForWidth())
        self.colorbutton4.setSizePolicy(sizePolicy)
        self.colorbutton4.setText(_fromUtf8(""))
        self.colorbutton4.setObjectName(_fromUtf8("colorbutton4"))
        self.gridLayout.addWidget(self.colorbutton4, 0, 3, 1, 1)
        self.colorbutton8 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton8.sizePolicy().hasHeightForWidth())
        self.colorbutton8.setSizePolicy(sizePolicy)
        self.colorbutton8.setText(_fromUtf8(""))
        self.colorbutton8.setObjectName(_fromUtf8("colorbutton8"))
        self.gridLayout.addWidget(self.colorbutton8, 1, 3, 1, 1)
        self.colorbutton6 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton6.sizePolicy().hasHeightForWidth())
        self.colorbutton6.setSizePolicy(sizePolicy)
        self.colorbutton6.setText(_fromUtf8(""))
        self.colorbutton6.setObjectName(_fromUtf8("colorbutton6"))
        self.gridLayout.addWidget(self.colorbutton6, 1, 1, 1, 1)
        self.colorbutton2 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton2.sizePolicy().hasHeightForWidth())
        self.colorbutton2.setSizePolicy(sizePolicy)
        self.colorbutton2.setText(_fromUtf8(""))
        self.colorbutton2.setObjectName(_fromUtf8("colorbutton2"))
        self.gridLayout.addWidget(self.colorbutton2, 0, 1, 1, 1)
        self.colorbutton7 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton7.sizePolicy().hasHeightForWidth())
        self.colorbutton7.setSizePolicy(sizePolicy)
        self.colorbutton7.setText(_fromUtf8(""))
        self.colorbutton7.setObjectName(_fromUtf8("colorbutton7"))
        self.gridLayout.addWidget(self.colorbutton7, 1, 2, 1, 1)
        self.colorbutton5 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton5.sizePolicy().hasHeightForWidth())
        self.colorbutton5.setSizePolicy(sizePolicy)
        self.colorbutton5.setText(_fromUtf8(""))
        self.colorbutton5.setObjectName(_fromUtf8("colorbutton5"))
        self.gridLayout.addWidget(self.colorbutton5, 1, 0, 1, 1)
        self.colorbutton1 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorbutton1.sizePolicy().hasHeightForWidth())
        self.colorbutton1.setSizePolicy(sizePolicy)
        self.colorbutton1.setText(_fromUtf8(""))
        self.colorbutton1.setObjectName(_fromUtf8("colorbutton1"))
        self.gridLayout.addWidget(self.colorbutton1, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab_1)
        self.pushButton.setGeometry(QtCore.QRect(290, 40, 112, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_1)
        self.pushButton_13.setGeometry(QtCore.QRect(260, 400, 112, 27))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_1)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 370, 151, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_1)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 80, 112, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_1)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 270, 261, 91))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.frame = QtGui.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(290, 160, 191, 211))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 91))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.pushButton_11 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.verticalLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.verticalLayout.addWidget(self.pushButton_12)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 173, 91))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.pushButton_10 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_15 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.verticalLayout_2.addWidget(self.pushButton_15)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 90, 261, 171))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 271, 41))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 260, 261, 101))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.wscolorbutton3 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton3.sizePolicy().hasHeightForWidth())
        self.wscolorbutton3.setSizePolicy(sizePolicy)
        self.wscolorbutton3.setText(_fromUtf8(""))
        self.wscolorbutton3.setObjectName(_fromUtf8("wscolorbutton3"))
        self.gridLayout_2.addWidget(self.wscolorbutton3, 0, 2, 1, 1)
        self.wscolorbutton4 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton4.sizePolicy().hasHeightForWidth())
        self.wscolorbutton4.setSizePolicy(sizePolicy)
        self.wscolorbutton4.setText(_fromUtf8(""))
        self.wscolorbutton4.setObjectName(_fromUtf8("wscolorbutton4"))
        self.gridLayout_2.addWidget(self.wscolorbutton4, 0, 3, 1, 1)
        self.wscolorbutton8 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton8.sizePolicy().hasHeightForWidth())
        self.wscolorbutton8.setSizePolicy(sizePolicy)
        self.wscolorbutton8.setText(_fromUtf8(""))
        self.wscolorbutton8.setObjectName(_fromUtf8("wscolorbutton8"))
        self.gridLayout_2.addWidget(self.wscolorbutton8, 1, 3, 1, 1)
        self.wscolorbutton6 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton6.sizePolicy().hasHeightForWidth())
        self.wscolorbutton6.setSizePolicy(sizePolicy)
        self.wscolorbutton6.setText(_fromUtf8(""))
        self.wscolorbutton6.setObjectName(_fromUtf8("wscolorbutton6"))
        self.gridLayout_2.addWidget(self.wscolorbutton6, 1, 1, 1, 1)
        self.wscolorbutton2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton2.sizePolicy().hasHeightForWidth())
        self.wscolorbutton2.setSizePolicy(sizePolicy)
        self.wscolorbutton2.setText(_fromUtf8(""))
        self.wscolorbutton2.setObjectName(_fromUtf8("wscolorbutton2"))
        self.gridLayout_2.addWidget(self.wscolorbutton2, 0, 1, 1, 1)
        self.wscolorbutton7 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton7.sizePolicy().hasHeightForWidth())
        self.wscolorbutton7.setSizePolicy(sizePolicy)
        self.wscolorbutton7.setText(_fromUtf8(""))
        self.wscolorbutton7.setObjectName(_fromUtf8("wscolorbutton7"))
        self.gridLayout_2.addWidget(self.wscolorbutton7, 1, 2, 1, 1)
        self.wscolorbutton5 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton5.sizePolicy().hasHeightForWidth())
        self.wscolorbutton5.setSizePolicy(sizePolicy)
        self.wscolorbutton5.setText(_fromUtf8(""))
        self.wscolorbutton5.setObjectName(_fromUtf8("wscolorbutton5"))
        self.gridLayout_2.addWidget(self.wscolorbutton5, 1, 0, 1, 1)
        self.wscolorbutton1 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wscolorbutton1.sizePolicy().hasHeightForWidth())
        self.wscolorbutton1.setSizePolicy(sizePolicy)
        self.wscolorbutton1.setText(_fromUtf8(""))
        self.wscolorbutton1.setObjectName(_fromUtf8("wscolorbutton1"))
        self.gridLayout_2.addWidget(self.wscolorbutton1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.pushButton_16 = QtGui.QPushButton(self.tab_3)
        self.pushButton_16.setGeometry(QtCore.QRect(260, 370, 191, 31))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.tab_3)
        self.pushButton_17.setGeometry(QtCore.QRect(260, 90, 191, 31))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 401, 51))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 320, 471, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.spinBox = QtGui.QSpinBox(self.tab_3)
        self.spinBox.setGeometry(QtCore.QRect(190, 170, 53, 21))
        self.spinBox.setProperty("value", 4)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.spinBox_2 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_2.setGeometry(QtCore.QRect(190, 210, 53, 21))
        self.spinBox_2.setProperty("value", 20)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(50, 170, 131, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(50, 210, 131, 19))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(10, 300, 441, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 130, 231, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton_14.setText(_translate("Dialog", "Cancel", None))
        self.pushButton.setText(_translate("Dialog", "New", None))
        self.pushButton_13.setText(_translate("Dialog", "Ok", None))
        self.pushButton_2.setText(_translate("Dialog", "Restore palette", None))
        self.pushButton_3.setText(_translate("Dialog", "Delete", None))
        self.pushButton_4.setText(_translate("Dialog", "h+", None))
        self.pushButton_8.setText(_translate("Dialog", "v-", None))
        self.pushButton_6.setText(_translate("Dialog", "v+", None))
        self.pushButton_7.setText(_translate("Dialog", "s+", None))
        self.pushButton_9.setText(_translate("Dialog", "s-", None))
        self.pushButton_5.setText(_translate("Dialog", "h-", None))
        self.label_2.setText(_translate("Dialog", "Hue", None))
        self.label_3.setText(_translate("Dialog", "Value", None))
        self.label_4.setText(_translate("Dialog", "Sat", None))
        self.label.setText(_translate("Dialog", "Nr of ui colors", None))
        self.pushButton_11.setText(_translate("Dialog", "8 Colors", None))
        self.pushButton_12.setText(_translate("Dialog", "4 Colors", None))
        self.label_5.setText(_translate("Dialog", "Color for panel", None))
        self.pushButton_10.setText(_translate("Dialog", "Like HpUx", None))
        self.pushButton_15.setText(_translate("Dialog", "Like recent release", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Tab 1", None))
        self.label_8.setText(_translate("Dialog", "Selected backdrop and color will\n"
"apply to the current workspace", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2", None))
        self.pushButton_16.setText(_translate("Dialog", "Use no theme", None))
        self.pushButton_17.setText(_translate("Dialog", "Use XFCE theme", None))
        self.label_6.setText(_translate("Dialog", "Apply CDE color sets to applications \n"
"and XFCE window manager decorations\n"
"and use backdrops:", None))
        self.label_7.setText(_translate("Dialog", "Use stand alone panel, without theming the\n"
"desktop environment:", None))
        self.label_9.setText(_translate("Dialog", "Border width", None))
        self.label_10.setText(_translate("Dialog", "Title height", None))
        self.label_11.setText(_translate("Dialog", "Xfce window decorations", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Page", None))

