#!/usr/bin/python
#import signal
#signal.signal(signal.SIGINT, signal.SIG_DFL)
import re
import os
import sys
import shutil
from PyQt4 import QtCore, QtGui
import MotifColors
import Globals
from MotifColors import colorize_bg
from MiscFun import *

screenHeight=600
def prepareBackDrops(opts):
    global screenHeight
    screenHeight=QtGui.QDesktopWidget().screenGeometry().height()
    for i in range(1,opts.nworkspaces+1):
        wscol=opts.workspacecolors[i]
        backdropsrc=opts.workspacebackdrops[i]
        if backdropsrc=="Gradient":scaletoheight=True
        else:scaletoheight=False
        prepareBackdrop(opts,i,backdropsrc,wscol,scaletoheight)
#all backdrops are called backdrop.pm, converted to backdrop.png
#def prepareBackdrop(self,i,backdropsrc,wscol,scaletoheight):
def prepareBackdrop(opts,i,backdropsrc,wscol,scaletoheight):
    print Globals.backdropdir
    global screenHeight
    scaleopts=''
    if scaletoheight:scaleopts='-geometry x{screenHeight}'.format(**globals())
    #colorize backdrop to given motif colorset. produces xpm
    palettefile=os.path.join(Globals.palettedir,opts.currentpalettefile)
    backdropin=os.path.join(Globals.backdropdir,"""{backdropsrc}.pm""".format(**locals()))
    backdropoutxpm=os.path.join(Globals.backdropdir,"""BACKDROP{i}.xpm""".format(**locals()))
    #todo checkfile shouldnt exit the program
    colorize_bg(checkFile(backdropin),backdropoutxpm,checkFile(palettefile),opts.ncolors,wscol)
    #convert original colored cde pm file to fit screen if required
    backdropoutpng=os.path.join(Globals.backdropdir,"""BACKDROP{i}.png""".format(**locals()))
    cmd="""
    convert \
    {scaleopts} \
    {backdropoutxpm} \
    {backdropoutpng}
    """.format(**locals())
    execWithShellThread(cmd)


def initXfceBackdrops(opts):
    cmd="""\
    xfconf-query -c xfce4-desktop -p /backdrop/single-workspace-mode -s false 
    """
    print cmd
    #execWithShell(cmd) 
    execWithShellThread(cmd) 
    #set xfce backrops to BACKDROPN.png. Those are generated by mainwindow.prepareBackDrops(self):
    N=opts.nworkspaces
    for i in range(1,N+1):
        setXfBackdrop(i)

def setXfBackdrop(workspacenr):
    bddir=Globals.backdropdir
    bgfile=os.path.join(Globals.backdropdir,"""BACKDROP{workspacenr}.png""".format(**locals()))
    #in eeeekseeffece we starte frum ze zerrrooo WHYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
    #why call workspace 1 worspace 0
    workspacenr-=1
    #needs full path (I now know after 3 days)
    cmd= """xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace{workspacenr}/last-image -s {bgfile} """.format(**locals())
    print cmd
    #execWithShell(cmd)
    execWithShellThread(cmd)
    cmd= """xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace{workspacenr}/image-style -s 2""".format(**locals())
    print cmd
    #execWithShell(cmd)
    execWithShellThread(cmd)
    #dontneed this becus aim switsing theme from cdetheme to cdetheme1 and vv (and it doesnt work anyway ahahahhahaha)
    #args = ["xfdesktop","--reload"]
    #subprocess.Popen(args)


